### PR TITLE
LRQA-74592 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-74592

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by epark18** [comment]
LGTM! 👍

**Comment by Sharryxue** [comment]
Hello @melodywu 
Please try to find the exist macro to instead of using the function. Thanks

**Comment by epark18** [comment]
Resent to: https://github.com/epark18/liferay-portal/pull/28

**Pull request closed without merging**
