### PR TITLE
LRQA-74231 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRQA-74231

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by epark18** [comment]
This looks good to me! Will resend with your other PR after change. Thank you for your patience!

**Comment by epark18** [comment]
This looks good to me! Will resend with your other PR after change. Thank you for your patience!

**Comment by epark18** [comment]
Resent to https://github.com/epark18/liferay-portal/pull/28.

**Pull request closed without merging**
